# Generated by Django 4.1.4 on 2023-01-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ekartapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("price", models.IntegerField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "product_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
    ]
